import networkx

redflags = [
    "Aksjonærlån",
    "Andre forhold",
    "Nedskrevet",
    "Tap/tapt",
    "konklusjon med forbehold",
    "negativ",
    "negativ konklusjon",
    "utfordringer med fortsatt drift",
    "usikkerhet vedrørende fortsatt drift",
    "konflikt",
    "handleplikt",
    "usikkerhet/usikkerheten",
    "skape tvil",
    "ulovlig",
    "ansvar for styret",
    "erstatningsansvar",
    "nderslag",
    "eversert",
    "ekstraordinært",
    "rstatning",
    "kattekrav",
    "nummerert brev",
    "søksmål/søksmålet",
    "presisering",
    "politianmeldt/politianmeldelse",
    "vesentlige mangler",
    "vesentlige mangler i intern kontroll",
    "mangelfull",
    "mangelfull intern kontroll",
]
