[project]
name = "gaij"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.2",
    "pillow>=10.4.0",
    "tesserocr>=2.7.1",
    "tqdm>=4.66.5",
]
